import { useState } from 'react'
import { motion } from 'framer-motion'

const TEXT = {
  en: { title: 'Doctor Report', generate: 'Generate Report', share: 'Share via WhatsApp', email: 'Share via Email', copy: 'Copy Report', copied: 'Copied!' },
  hi: { title: 'डॉक्टर रिपोर्ट', generate: 'रिपोर्ट बनाएं', share: 'WhatsApp पर भेजें', email: 'Email पर भेजें', copy: 'कॉपी करें', copied: 'कॉपी हो गया!' },
}
export default function DoctorReport({ cycleData, logs, lang }) {
  const t = TEXT[lang] || TEXT.en
  const [generated, setGenerated] = useState(false)
  const [copied, setCopied] = useState(false)

  const { avgLength, periodLength, daysUntilNext} = cycleData

  const topSymptoms = logs
    .flatMap(l => l.symptoms)
    .reduce((acc, s) => { acc[s] = (acc[s] || 0) + 1; return acc }, {})

  const sortedSymptoms = Object.entries(topSymptoms)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)

  const avgPain = logs.length
    ? (logs.reduce((sum, l) => sum + l.pain, 0) / logs.length).toFixed(1)
    : 0

  const reportText = `
🌸 BLOOMCYCLE - PCOD HEALTH REPORT
Generated: ${new Date().toLocaleDateString('en-IN')}
━━━━━━━━━━━━━━━━━━━━━━━━

📅 CYCLE INFORMATION
- Average cycle length: ${avgLength} days
- Period duration: ${periodLength} days
- Next period in: ${daysUntilNext} days

📊 SYMPTOM SUMMARY (Last ${logs.length} logs)
- Average pain level: ${avgPain}/10
${sortedSymptoms.map(([s, count]) => `• ${s}: ${count} times`).join('\n')}

📝 RECENT LOGS
${logs.slice(0, 5).map(l => `• ${l.date}: Mood-${l.mood}, Pain-${l.pain}/10, ${l.symptoms.join(', ')}`).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━
Generated by BloomCycle App
Please review with your gynaecologist
  `.trim()

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  const handleWhatsApp = () => {
    const encoded = encodeURIComponent(reportText)
    window.open(`https://wa.me/?text=${encoded}`, '_blank')
  }

  const handleEmail = () => {
    const subject = encodeURIComponent('My PCOD Health Report - BloomCycle')
    const body = encodeURIComponent(reportText)
    window.open(`mailto:?subject=${subject}&body=${body}`, '_blank')
  }

 
  return (
    <div style={{ padding: '20px 16px' }}>

      {/* Header banner */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        style={{ background: 'linear-gradient(135deg, var(--pink-400), var(--purple-400))', borderRadius: 'var(--radius-lg)', padding: '20px', marginBottom: 16, textAlign: 'center', color: 'white' }}
      >
        <div style={{ fontSize: 40, marginBottom: 8 }}>🩺</div>
        <div style={{ fontSize: 18, fontWeight: 600, marginBottom: 4 }}>{t.title}</div>
        <div style={{ fontSize: 13, opacity: 0.9 }}>Share your health data with your doctor</div>
      </motion.div>

      {/* Cycle summary cards */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10, marginBottom: 16 }}>
        {[
          { label: 'Avg Cycle', value: avgLength, unit: 'days', icon: '📅' },
          { label: 'Avg Pain', value: avgPain, unit: '/10', icon: '⚡' },
          { label: 'Logs', value: logs.length, unit: 'total', icon: '📝' },
        ].map(s => (
          <div key={s.label} style={{ background: 'white', borderRadius: 'var(--radius-md)', border: '1px solid var(--pink-200)', padding: '12px 8px', textAlign: 'center' }}>
            <div style={{ fontSize: 20, marginBottom: 4 }}>{s.icon}</div>
            <div style={{ fontSize: 20, fontWeight: 600, color: 'var(--pink-400)' }}>{s.value}</div>
            <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>{s.label}</div>
          </div>
        ))}
      </div>

      {/* Top symptoms */}
      <div style={{ background: 'white', borderRadius: 'var(--radius-lg)', border: '1px solid var(--pink-200)', padding: '16px', marginBottom: 16 }}>
        <div style={{ fontSize: 15, fontWeight: 500, color: 'var(--pink-600)', marginBottom: 12 }}>🌸 Top Symptoms</div>
        {sortedSymptoms.length > 0 ? sortedSymptoms.map(([symptom, count]) => (
          <div key={symptom} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid var(--pink-100)' }}>
            <span style={{ fontSize: 13, color: 'var(--text-primary)' }}>{symptom}</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <div style={{ width: 80, height: 6, background: 'var(--pink-100)', borderRadius: 99, overflow: 'hidden' }}>
                <motion.div
                  initial={{ width: 0 }}
                  animate={{ width: `${(count / logs.length) * 100}%` }}
                  transition={{ duration: 0.8 }}
                  style={{ height: '100%', background: 'var(--pink-400)', borderRadius: 99 }}
                />
              </div>
              <span style={{ fontSize: 12, color: 'var(--pink-400)', fontWeight: 500 }}>{count}x</span>
            </div>
          </div>
        )) : (
          <p style={{ fontSize: 13, color: 'var(--text-muted)' }}>No symptoms logged yet. Start logging in the Symptoms tab!</p>
        )}
      </div>

      {/* Report preview */}
      {generated && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          style={{ background: 'var(--pink-50)', borderRadius: 'var(--radius-lg)', border: '1px solid var(--pink-200)', padding: '16px', marginBottom: 16, fontFamily: 'monospace', fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.8, whiteSpace: 'pre-wrap' }}
        >
          {reportText}
        </motion.div>
      )}

      {/* Buttons */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        <motion.button
          whileTap={{ scale: 0.97 }}
          onClick={() => setGenerated(true)}
          style={{ width: '100%', padding: '14px', background: 'linear-gradient(135deg, var(--pink-400), var(--purple-400))', color: 'white', borderRadius: 'var(--radius-md)', fontSize: 15, fontWeight: 600, cursor: 'pointer', border: 'none', fontFamily: 'var(--font-body)' }}
        >
          📋 {t.generate}
        </motion.button>

        {generated && (
          <>
            <motion.button
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              whileTap={{ scale: 0.97 }}
              onClick={handleWhatsApp}
              style={{ width: '100%', padding: '14px', background: '#25D366', color: 'white', borderRadius: 'var(--radius-md)', fontSize: 15, fontWeight: 600, cursor: 'pointer', border: 'none', fontFamily: 'var(--font-body)' }}
            >
              📱 {t.share}
            </motion.button>

            <motion.button
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              whileTap={{ scale: 0.97 }}
              onClick={handleEmail}
              style={{ width: '100%', padding: '14px', background: 'var(--purple-400)', color: 'white', borderRadius: 'var(--radius-md)', fontSize: 15, fontWeight: 600, cursor: 'pointer', border: 'none', fontFamily: 'var(--font-body)' }}
            >
              📧 {t.email}
            </motion.button>

            <motion.button
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 }}
              whileTap={{ scale: 0.97 }}
              onClick={handleCopy}
              style={{ width: '100%', padding: '14px', background: copied ? 'var(--teal-400)' : 'white', color: copied ? 'white' : 'var(--pink-600)', borderRadius: 'var(--radius-md)', fontSize: 15, fontWeight: 600, cursor: 'pointer', border: '1.5px solid var(--pink-200)', fontFamily: 'var(--font-body)' }}
            >
              {copied ? '✓ ' + t.copied : '📋 ' + t.copy}
            </motion.button>
          </>
        )}
      </div>

      <div style={{ background: 'var(--amber-50)', borderRadius: 'var(--radius-md)', padding: '12px 14px', marginTop: 16, marginBottom: 20, border: '1px solid rgba(186,117,23,0.2)' }}>
        <p style={{ fontSize: 12, color: 'var(--amber-400)', lineHeight: 1.6 }}>
          ⚠️ This report is for reference only. Always consult a qualified gynaecologist or endocrinologist for PCOD diagnosis and treatment.
        </p>
      </div>
    </div>
  )
}